### ISSUE TITLE
ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by shaneshbi** [kepei1106/SentenceFunction#3]
ValueError: setting an array element with a sequence.
global step 0 learning rate 0.1000 step-time 0.00 perplexity [1.00] kl_loss [0.00] dec_loss [0.00] dis_loss [0.00]
Traceback (most recent call last):
  File "main.py", line 342, in <module>
    evaluate(model, sess, data_dev)
  File "main.py", line 202, in evaluate
    outputs = model.step_decoder(sess, batched_data, forward_only=True, global_t = FLAGS.full_kl_step)
  File "/home/Documents/code/sentence-function/model.py", line 262, in step_decoder
    return session.run(output_feed, input_feed)
  File "/home/anaconda3/envs/conda36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/anaconda3/envs/conda36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1121, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/anaconda3/envs/conda36/lib/python3.6/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.

error occurs when execute sess.run()
it seems like to be some input dim errors .
i tried many ways  but haven't do with it
can u help solve it?

**Comment by shaneshbi** [comment]
@kepei1106

**Comment by shaneshbi** [comment]
sovled by adjusting the .label files

**Comment by libing125** [comment]
> sovled by adjusting the .label files

how do you adjust it? thanks
